name: sama_app
description: "سَما — تطبيق مكالمات صوت وفيديو يشتغل بكفاءة على شبكات الإنترنت الفضائي والأرضي، لحسابات الأفراد والشركات."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.7
  web_socket_channel: ^3.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
