name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Generate Android platform files
        run: flutter create --platforms=android .
        working-directory: sama_app
      - run: flutter pub get
        working-directory: sama_app
      - run: flutter build apk --debug
        working-directory: sama_app
      - uses: actions/upload-artifact@v4
        with:
          name: sama-app-debug-apk
          path: sama_app/build/app/outputs/flutter-apk/app-debug.apk
